# Build
FROM node:20-alpine AS build

# Work dir inside container
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy all files
COPY . .

# Build the app
RUN npm run build

# Nginx to serve the files
FROM nginx:alpine

# Copy already copied files to nginx folder
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Start
CMD ["nginx", "-g", "daemon off;"]
