version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: minitwitter-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=MiniTwitterDb;User Id=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True"
    depends_on:
      - mssql
    ports:
      - "8080:8080"
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: minitwitter-mssql
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD}" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: minitwitter-sqlpad
    ports:
      - "3000:3000"
    environment:
      - SQLPAD_ADMIN=admin@example.com
      - SQLPAD_ADMIN_PASSWORD=admin
      - SQLPAD_APP_LOG_LEVEL=debug

      # Connection settings
      - SQLPAD_CONNECTIONS__minitwitter__name=MiniTwitter
      - SQLPAD_CONNECTIONS__minitwitter__driver=sqlserver
      - SQLPAD_CONNECTIONS__minitwitter__host=minitwitter-mssql
      - SQLPAD_CONNECTIONS__minitwitter__port=1433
      - SQLPAD_CONNECTIONS__minitwitter__database=MiniTwitterDb
      - SQLPAD_CONNECTIONS__minitwitter__username=sa
      - SQLPAD_CONNECTIONS__minitwitter__password=${SA_PASSWORD}
      - SQLPAD_CONNECTIONS__minitwitter__trustServerCertificate=true

    depends_on:
      mssql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mssql-data:
